### PR TITLE
Build with Github Actions.

### PR DESCRIPTION
**Pull request by auouymous**
This was working at https://github.com/auouymous/gpodder-osx-bundle/runs/7514294773?check_suite_focus=true but then stopped with "waiting for a runner".

Available software is at https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md

### CODE REVIEW

**Comment by auouymous** [comment]
https://github.com/auouymous/gpodder-osx-bundle/runs/7514294773?check_suite_focus=true#step:3:21176 is at the end of the call to https://gitlab.gnome.org/GNOME/gtk-osx/-/blob/master/gtk-osx-setup.sh in bootstrap.sh.

**Comment by elelay** [comment]
you can try to update to the latest commit from https://gitlab.gnome.org/GNOME/gtk-osx/-/tree/master in https://github.com/gpodder/gpodder-osx-bundle/blob/master/bootstrap.sh#L18

**Comment by auouymous** [comment]
https://github.com/auouymous/gpodder-osx-bundle/actions

It stops on the same line, and then times out after 6 hours.

```
The job running on runner Hosted Agent has exceeded the maximum execution time of 360 minutes.
```

If it would work, we have 6 hours to build with 3 cores and 14GB of ram.

**Comment by auouymous** [comment]
It does reach the end of `./_gtk-osx/gtk-osx-setup.sh` but never returns to `bootstrap.sh` due to piping `yes` into it. Removing the `yes` worked and it continued to the `build.sh` step. Hopefully it will complete all steps, and then I can remove the test commit and we can figure out how to handle the artifact.

**Comment by auouymous** [comment]
@elelay https://github.com/gpodder/gpodder-osx-bundle/pull/23/commits/9102f6f979e1251403a26efc1994127f53652861 is an attempt to add brotli, which is also needed by freetype-no-harfbuzz in github's virtual environment.

**Comment by elelay** [comment]
Why is it not required when building on macOS 10.9 and on circleci?

**Comment by auouymous** [comment]
Github 10.15 and 11 both require it. The logs while building freetype-no-harfbuzz throw pkg-config warnings about BrotliDec and mismatched macos versions for libbrotlidec. So maybe configure found github's brotli and used it, while circleci doesn't have it installed.

```
[41/42] Linking C shared library libfreetype.6.17.4.dylib
ld: warning: dylib (/usr/local/lib/libbrotlidec.dylib) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: dylib (/usr/local/lib/libbrotlidec.dylib) was built for newer macOS version (11.0) than being linked (10.9)
[42/42] Creating library symlink libfreetype.6.dylib libfreetype.dylib
```

All I found was https://mail.gnome.org/archives/gtk-osx-users-list/2021-May/msg00012.html.

But the build now reaches gobject-introspection before failing...

**Comment by auouymous** [comment]
It finally works!

https://github.com/auouymous/gpodder-osx-bundle/actions/runs/2843445616 is a workflow with artifacts. The action automatically zips all artifacts (not optional) and the new github_release.py unzips them. The artifacts are also not public, so switching gpodder to github actions wouldn't allow mac users to download artifacts like appveyor. There is however https://nightly.link if we want to authorize them, but mac users would need to unzip the artifact.

I haven't done it yet, but README.asciidoc will also need updating because `--circle-build <num>` is now `--github-workflow <num>`, where `<num>` is the 2843445616 in the above URL. There is othe information in the readme that is out of date.

**Comment by elelay** [comment]
And the final app works :partying_face: 
Great, thanks! I've just cancelled the circleci plan.

Regarding downloadable artifacts, nightly.link seems solid: no write permissions to the repo + the bot with link in a comment.

**Comment by auouymous** [comment]
I updated the README and all gtk-osx modules to hopefully fix the hidpi issue. Does the https://github.com/auouymous/gpodder-osx-bundle/actions/runs/2938755720 artifact work and should we merge this to test with gpodder?

**Comment by elelay** [comment]
It should be merged since it builds!
Now to test with gpodder. The best is for testers to 
1. download and unzip the bundle somewhere (let's say `~/Desktop/bundle`)
````
git clone https://github.com/gpodder/gpodder.git
cd gpodder
./tools/mac-osx/release_on_mac.sh ~/Desktop/bundle/pythonbase-22.7.28-8-g1e3e420.zip
```` 

to produce `tools/mac-osx/_build/gPodder.app` and test with it.
Otherwise the README procedure (tag, upload artifact, update gpodder/.circleci/config.yml) must be followed.

**Comment by auouymous** [comment]
The gpodder build is "failing" at https://circleci.com/api/v1.1/project/github/gpodder/gpodder/840/output/102/0?file=true&allocation-id=630b0824f0ec056df39a6921-0-build%2F1B3616C6 but not showing an error. Do you know why brotli is not finding Python.h?

It worked 14 days ago when https://github.com/gpodder/gpodder/pull/1369 was merged. And stopped working 3 days ago when https://github.com/gpodder/gpodder/pull/1356 was merged.

**Comment by auouymous** [comment]
`-I/Users/distiller/project/tools/mac-osx/_build/gPodder.app/Contents/Resources/include/python3.9` changed to `-I/Users/distiller/project/_home/gtk/inst/include/python3.9` when compiling brotli files which explains why Python.h can not be found. It is building the same brotli 1.0.9 package with same hash, so nothing in the brotli package changed.

**Comment by elelay** [comment]
A change in setuptools did it. See working https://app.circleci.com/pipelines/github/gpodder/gpodder/478/workflows/1ab16871-8d9e-4a6e-9a3f-e08cd0e7e525/jobs/846 for commit https://github.com/gpodder/gpodder/commit/f5a8e54660eb442eaf98c8c809a93ed464f10148

**Comment by auouymous** [comment]
Thank you!

**Pull request merged**
